export enum OperationsEnum {
  REGISTRATION_USER = 'REGISTRATION_USER',
  REGISTRATION_WITH_CREDENTIALS = 'REGISTRATION_WITH_CREDENTIALS',
  PASSWORD_RECOVERY = 'PASSWORD_RECOVERY',
  PHONE_RECOVERY = 'PHONE_RECOVERY',
  EMAIL_RECOVERY = 'EMAIL_RECOVERY',
}
