# vim: tabstop=2 shiftwidth=2 expandtab
version: '3'

services:
  gateway:
    image: node:20-alpine
    container_name: gateway
    restart: unless-stopped
    environment:
      ENV: development
    ports:
      - ${MICROSERVICES_GATEWAY_PORT}:${MICROSERVICES_GATEWAY_OPEN_PORT}
    volumes:
      - ./:/workspace
      - backend_nm:/workspace/node_modules
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /workspace
    command: /bin/sh -c "yarn install && yarn start:dev"
    networks:
      - api-network

volumes:
  backend_nm:

networks:
  api-network:
    name: api-network
    driver: bridge
    external: true