export enum CommonExceptionEnum {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  DATA_DUPLICATION = 'DATA_DUPLICATION',
  VALIDATION = 'VALIDATION',
}
