export enum JwtExceptionEnum {
  ACCESS_TOKEN_UNCORRECTED = 'ACCESS_TOKEN_UNCORRECTED',
  REFRESH_TOKEN_UNCORRECTED = 'REFRESH_TOKEN_UNCORRECTED',
  WRONG_SECRET_PROVIDER_ERROR = 'WRONG_SECRET_PROVIDER_ERROR',
  PAYLOAD_STRING_ERROR = 'PAYLOAD_STRING_ERROR',
  USED_OLD_VERSION_METHOD_WITHOUT_SECRET = 'USED_OLD_VERSION_METHOD_WITHOUT_SECRET',
  LIFE_TIME_TOKEN_UNCORRECTED = 'LIFE_TIME_TOKEN_UNCORRECTED',
  JWT_EXPIRED = 'JWT_EXPIRED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
