export enum CommentsExceptionEnum {
  SCHEDULER_DROP_COMMENT_ERROR = 'SCHEDULER_DROP_COMMENT_ERROR',

  FAILED_TO_UPDATE_COMMENT = 'FAILED_TO_UPDATE_COMMENT',
  COMMENTS_IS_NOT_FOUND = 'COMMENTS_IS_NOT_FOUND',
}
